import "server-only";

import { PDFDocument, StandardFonts, rgb, type PDFFont } from "pdf-lib";

import type { InterviewReport } from "@/modules/interview/config";

// Server-side PDF export of a saved interview report (Pro feature). Uses pdf-lib
// (already a dependency) — no external API, so it's free to run. Simple flowing
// layout with word wrapping and automatic pagination.
const A4: [number, number] = [595.28, 841.89];
const MARGIN = 50;
const CONTENT_W = A4[0] - MARGIN * 2;
const PRIMARY = rgb(0.43, 0.16, 0.85);
const MUTED = rgb(0.42, 0.45, 0.5);
const TEXT = rgb(0.1, 0.11, 0.13);

export async function buildInterviewPdf(
  report: InterviewReport,
  label: string,
  dateStr: string,
): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);

  let page = doc.addPage(A4);
  let y = A4[1] - MARGIN;

  const wrap = (text: string, f: PDFFont, size: number, maxW: number): string[] => {
    const lines: string[] = [];
    for (const paragraph of String(text).split("\n")) {
      let line = "";
      for (const word of paragraph.split(/\s+/)) {
        const test = line ? `${line} ${word}` : word;
        if (f.widthOfTextAtSize(test, size) > maxW && line) {
          lines.push(line);
          line = word;
        } else {
          line = test;
        }
      }
      lines.push(line);
    }
    return lines;
  };

  const write = (
    text: string,
    opts: { size?: number; bold?: boolean; color?: ReturnType<typeof rgb>; gap?: number; indent?: number } = {},
  ) => {
    const size = opts.size ?? 11;
    const f = opts.bold ? bold : font;
    const color = opts.color ?? TEXT;
    const indent = opts.indent ?? 0;
    const lh = size * 1.45;
    for (const ln of wrap(text, f, size, CONTENT_W - indent)) {
      if (y - lh < MARGIN) {
        page = doc.addPage(A4);
        y = A4[1] - MARGIN;
      }
      page.drawText(ln, { x: MARGIN + indent, y: y - size, size, font: f, color });
      y -= lh;
    }
    if (opts.gap) y -= opts.gap;
  };

  const section = (title: string) => write(title, { size: 13, bold: true, color: PRIMARY, gap: 4 });

  // Header
  write("Interview Report", { size: 22, bold: true, color: PRIMARY, gap: 2 });
  write(label, { size: 12, color: MUTED, gap: 1 });
  write(dateStr, { size: 10, color: MUTED, gap: 14 });

  // Score
  write(`Overall score: ${report.overallScore}/100 — ${report.readiness}`, { size: 14, bold: true, gap: 6 });
  if (report.summary) write(report.summary, { gap: 14 });

  if (report.strengths?.length) {
    section("Strengths");
    for (const s of report.strengths) write(`•  ${s}`, { indent: 8, gap: 1 });
    y -= 10;
  }
  if (report.improvements?.length) {
    section("Areas to improve");
    for (const s of report.improvements) write(`•  ${s}`, { indent: 8, gap: 1 });
    y -= 10;
  }
  if (report.focusAreas?.length) {
    section("What to study next");
    for (const s of report.focusAreas) write(`•  ${s}`, { indent: 8, gap: 1 });
    y -= 10;
  }

  if (report.perQuestion?.length) {
    section("Question-by-question");
    report.perQuestion.forEach((q, i) => {
      write(`Q${i + 1}. ${q.question}`, { bold: true, gap: 1 });
      write(`Score: ${q.score}/5`, { size: 10, color: MUTED, gap: 2 });
      if (q.feedback) write(`Feedback: ${q.feedback}`, { gap: 2 });
      if (q.modelAnswer) write(`Model answer: ${q.modelAnswer}`, { color: MUTED, gap: 12 });
    });
  }

  write("Generated by OhoTool · ohotool.com", { size: 9, color: MUTED });

  return doc.save();
}
